"""Add registry fields

Revision ID: 9e33f8317ca3
Revises: 5f04bfb10ce5
Create Date: 2026-08-26 14:50:21.733707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e33f8317ca3'
down_revision: Union[str, Sequence[str], None] = '5f04bfb10ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_promotion_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_version_id', sa.String(), nullable=False),
    sa.Column('previous_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_promotion_history_model_version_id'), 'model_promotion_history', ['model_version_id'], unique=False)
    op.add_column('model_versions', sa.Column('training_run_id', sa.String(), nullable=True))
    op.add_column('model_versions', sa.Column('git_commit', sa.String(), nullable=True))
    op.add_column('model_versions', sa.Column('quality_score', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_versions', 'quality_score')
    op.drop_column('model_versions', 'git_commit')
    op.drop_column('model_versions', 'training_run_id')
    op.drop_index(op.f('ix_model_promotion_history_model_version_id'), table_name='model_promotion_history')
    op.drop_table('model_promotion_history')
    # ### end Alembic commands ###
